# Generated by Django 3.2 on 2021-05-07 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='livro',
            old_name='status',
            new_name='tipo',
        ),
    ]
